#!/bin/bash

# esm postrm script
# we should activate set -e
# In case of failure it should quit 

function remove ()
{
    service lighttpd stop
    userdel esm
    rm -f /etc/sudoers.d/99-flash-esm
    [ -L /etc/lighttpd/lighttpd.conf ] && rm -f /etc/lighttpd/lighttpd.conf
    rm -f /etc/lighttpd/lighttpd.conf.esm.dist
    mv /etc/lighttpd/lighttpd.conf.dist /etc/lighttpd/lighttpd.conf
}

case "$1" in
    remove|purge)               remove          ;;
esac
